# Generated by Django 5.2.3 on 2025-12-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.URLField(blank=True, help_text='لطفا لینک تصویر پروفایل خود را وارد کنید', max_length=500, null=True, verbose_name='عکس پروفایل'),
        ),
    ]
