# Generated by Django 5.2.3 on 2025-12-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='لطفا لینک تصویر پروژه از ابرآروان را قرار دهید', max_length=500, null=True, verbose_name='لینک تصویر پروژه'),
        ),
    ]
