# Generated by Django 5.2.3 on 2025-10-10 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دوره')),
                ('level', models.IntegerField(choices=[(1, 'مقدماتی'), (2, 'متوسط'), (3, 'پیشرفته')], verbose_name='سطح آموزش')),
                ('length', models.IntegerField(verbose_name='طول دوره')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='گواهینامه دارد؟')),
                ('has_exam', models.BooleanField(default=False, verbose_name='آزمون دارد؟')),
                ('course_format', models.CharField(choices=[('video', 'ویدیویی'), ('text', 'متنی'), ('mixed', 'ترکیبی')], max_length=50, verbose_name='فرمت آموزش')),
                ('software', models.TextField(blank=True, null=True, verbose_name='نرم\u200cافزار موردنیاز')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت دوره')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت با تخفیف')),
                ('demo_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر دمو')),
                ('main_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر اصلی')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='دسته بندی')),
                ('prerequisite', models.ManyToManyField(blank=True, related_name='required_for', to='course.course', verbose_name='پیش\u200cنیازها')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فصل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان درس')),
                ('description', models.TextField(verbose_name='محتوای درس')),
                ('video', models.CharField(blank=True, help_text='لینک ویدیو را وارد کنید', max_length=500, null=True, verbose_name='ویدیو')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.chapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
