# Generated by Django 5.2.3 on 2025-10-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='demo_pic',
            field=models.URLField(blank=True, help_text='لینک تصویر دمو را وارد کنید', max_length=500, null=True, verbose_name='لینک تصویر دمو'),
        ),
        migrations.AlterField(
            model_name='course',
            name='main_pic',
            field=models.ImageField(blank=True, help_text='لینک تصویر اصلی را وارد کنید', max_length=500, null=True, upload_to='', verbose_name='لینک تصویر اصلی'),
        ),
    ]
