# Generated by Django 5.2.3 on 2025-10-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_demo_pic_alter_course_main_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='main_pic',
            field=models.URLField(blank=True, help_text='لینک تصویر اصلی را وارد کنید', max_length=500, null=True, verbose_name='لینک تصویر اصلی'),
        ),
    ]
