# Generated by Django 5.2.3 on 2025-11-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
